#spring:
  #datasource:
    #url: jdbc:h2:file:./visit_beta2
    #driverClassName: org.h2.Driver
    #username: sa
    #password: password
  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
      #ddl-auto: update
  #h2:
    #console:
      #enabled: true
      
      # Configuration MySQL
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/visitdb
      username: root
      password: 
     # Configuration Hibernate
   jpa: 
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
         ddl-auto: update

visit:
  app:
    jwtSecret: ======================visit=Spring===========================
    jwtExpirationMs: 86400000